#Welcome in the popTube configuration file !
#Database configuration

host=localhost
user=root
passwd=root
db=sys
SDL_WindowFlags=SDL_WINDOW_FULLSCREEN
SDL_WindowFlags=SDL_WINDOW_HIDDEN
SDL_WindowFlags=SDL_WINDOW_SHOWN
#SDL_WindowFlags=SDL_WINDOW_BORDERLESS
#SDL_WindowFlags=SDL_WINDOW_RESIZABLE
#SDL_WindowFlags=SDL_WINDOW_MINIMIZED
#SDL_WindowFlags=SDL_WINDOW_MAXIMIZED
SDL_WindowFlags=SDL_WINDOW_INPUT_GRABBED
#SDL_WindowFlags=SDL_WINDOW_INPUT_FOCUS
#SDL_WindowFlags=SDL_WINDOW_FULLSCREEN_DESKTOP
#SDL_WindowFlags=SDL_WINDOW_FOREIGN
#SDL_WindowFlags=SDL_WINDOW_ALLOW_HIGHDPI
